In [1]:
import numpy as np

## Array in numpy

In [2]:
a=np.array([20,30,40,50])
print(a)

[20 30 40 50]


In [5]:
a=np.array([20,30,40,50])
print(type(a))                               
print(a.dtype)                                # To check data type

<class 'numpy.ndarray'>
int32


In [6]:
a=np.array([2.20,30,40,50])
print(a)
print(a.dtype)

[ 2.2 30.  40.  50. ]
float64


In [7]:
a=np.array(["2",30,40,50])
print(a)
print(a.dtype)

['2' '30' '40' '50']
<U11


## Working with array dimension

In [8]:
a=np.array(["2",30,40,50])
print(a)
print(a.ndim)

['2' '30' '40' '50']
1


In [9]:
# 0dim
ab=np.array(90)
print(ab)
print(ab.ndim)

90
0


In [10]:
ab=np.array([90])
print(ab)
print(ab.ndim)

[90]
1


In [12]:
ab=np.array([[[2,3,4,5]],[[2,3,4,5]]])
print(ab)
print(ab.ndim)
print(ab.shape)                     # Working with shape

[[[2 3 4 5]]

 [[2 3 4 5]]]
3
(2, 1, 4)


In [13]:
# creating zeros array
ab=np.zeros([2,2])
print(ab)

[[0. 0.]
 [0. 0.]]


In [14]:
ab=np.zeros([4,5])
print(ab)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# Creating ones array
ab=np.ones([4,5])
print(ab)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# Array Reshape
a=np.array([21,32,31,24,15,61,51,17])
ab=a.reshape(2,4)
ab

array([[21, 32, 31, 24],
       [15, 61, 51, 17]])

In [17]:
# Working with array Slicing
a=np.array([15,61,51,17,22,15,61,99])
print(a[3:])

[17 22 15 61 99]


In [18]:
a=np.array([15,61,51,17,22,15,61,99])
print(a[0])
print(a[1])

15
61


In [19]:
a=np.array([[15,61,51,17,22,15,61,99],[22,31,13,14,25,16,66,89]])
print(a[0])
print(a[1])

[15 61 51 17 22 15 61 99]
[22 31 13 14 25 16 66 89]


In [20]:
a=np.array([[15,61,51,17,22,15,61,99],[22,31,13,14,25,16,66,89]])
ab=a[-1,:3]
print(ab)
for x in ab:
    print(x)

[22 31 13]
22
31
13


In [21]:
# Working with array spliting
a=np.array([15,61,51,17,22,15,61,99])
ab=np.array_split(a,4)
ab

[array([15, 61]), array([51, 17]), array([22, 15]), array([61, 99])]

In [22]:
a=np.array([15,61,51,17,22,15,61,99])
ab=np.array_split(a,10)
ab

[array([15]),
 array([61]),
 array([51]),
 array([17]),
 array([22]),
 array([15]),
 array([61]),
 array([99]),
 array([], dtype=int32),
 array([], dtype=int32)]